
// English patterns;
EnglishPatterns = [
	/I need (.*)/i,
	/Because you don't (.*)/i,
	/Because I can't (.*)/i,
	/I can't (.*)/i,
	/I am (.*)/i,
	/You are (.*)/i,
	/What (.*)/i,
	/How (.*)/i,
	/Because (.*)/i,
	/(.*) sorry (.*)/i,
	/(Hi|Hello)(.*)/i,
	/I think (.*)/i,
	/(.*) friend (.*)/i,
	/Yes/i,
	/(.*) computer(.*)/i,
	/This is (.*)/i,
	/You can (.*)/i,
	/I can (.*)/i,
	/I don't (.*)/i,
	/I feel (.*)/i,
	/I have (.*)/i,
	/I can (.*)/i,
	/There (.*)/i,
	/Mine (.*)/i,
	/You (.*)/i,
	/Because (.*)/i,
	/I want (.*)/i,
	/(.*) mother (.*)/i,
	/(.*) father (.*)/i,
	/(.*) child (.*)/i,
	/(Bye|Good Bye)/i
];
